### PR TITLE
upgrade to webrtc-adapter v1.0

### PR DESCRIPTION
**Pull request by tgabi333**
upgrade devDependencies

### CODE REVIEW

**Comment by fippo** [comment]
LGTM, go ahead ;-)

**Comment by tgabi333** [comment]
I've got this: "Only those with write access to this repository can merge pull requests."

**Comment by fippo** [comment]
does it work now? managing github teams...

**Comment by tgabi333** [comment]
Yep, tnx

**Comment by fippo** [comment]
published as 1.1.6, thanks!

**Pull request merged**
